### ISSUE TITLE
Platforms

### ISSUE THREAD

**Issue by c-andrews** [danwilson/social-auth-plugin#2]
Hi, Could you tell me if you are looking to port your plugin to Android or any other platforms?

Thanks,
Chris

**Comment by danwilson** [comment]
I'm looking into the options, but right now this plugin is tied into the OS-level Twitter/Facebook integration that iOS has.  Android doesn't really have an equivalent, but Windows Phone 8 might have something at a similar level, so it would be the next to tackle.  So for now it is going to be iOS only.  If Android or other platforms provide an equivalent mechanism I will look into it.  Thanks!
