### ISSUE TITLE
Error when building my app.

### ISSUE THREAD

**Issue by gianebao** [danwilson/social-auth-plugin#3]
I'm encountering this error when i run `build`.

...platforms/ios/HelloCordova/Plugins/com.danielcwilson.plugins.socialauth/SocialAuthPlugin.h:6:9: fatal error: 
      'social/Social.h' file not found
# import "social/Social.h"

**Comment by danwilson** [comment]
It sounds like the Social.framework was not properly added.  Was this added via the CLI?
